// Uncomment the code below and write your tests
// eslint-disable-next-line prettier/prettier
import { MyAwesomeError, rejectCustomError, resolveValue, throwCustomError, throwError } from '.';

describe('resolveValue', () => {
  test('should resolve provided value', async () => {
    const value = 'test';
    const result = await resolveValue(value);
    expect(result).toBe(value);
  });
});

describe('throwError', () => {
  test('should throw error with provided message', () => {
    const message = 'Custom error message';
    expect(() => throwError(message)).toThrowError(new Error(message));
  });

  test('should throw error with default message if message is not provided', () => {
    expect(() => throwError()).toThrowError(new Error('Oops!'));
  });
});

describe('throwCustomError', () => {
  test('should throw custom error', () => {
    expect(() => throwCustomError()).toThrowError(new MyAwesomeError());
  });
});

describe('rejectCustomError', () => {
  test('should reject custom error', async () => {
    await expect(rejectCustomError()).rejects.toThrowError(
      new MyAwesomeError(),
    );
  });
});
